inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

Style/Documentation:
  Enabled: false

# TODO(uwe): Remove after Rubocop 1.0 is released
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
# ODOT
