sudo: false
cache: bundler
services:
  - postgresql
notifications:
  irc:
    channels:
      - "irc.freenode.org#ruboto"
    use_notice: true
    skip_join: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe0d532fe5bef5b7288c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
